# Generated by Django 3.2.15 on 2022-08-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todouser",
            name="age",
        ),
    ]
